version: '3.2'

services:
  api:
    build:
      context: #TBW
      dockerfile: ./Dockerfile
    # TBW

  apidb:
    image: postgres:10.1
    # TBW

networks:
  db_nw:
    driver: bridge

volumes:
  docker_data:
