version: '3.2'

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: >
      bash -c "set -x;
               cd /opt/api;
               while true; do python app.py; done;"
    container_name: poc-api
    depends_on:
      - apidb
    env_file:
        - ./.env
    environment:
      - POSTGRES_URL=postgresql://poc_user:poc_password@apidb/poc_api
    networks:
      - db_nw
    ports:
      - 80:80
    volumes:
      - ./api:/opt/api

  apidb:
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on
    container_name: poc-apidb
    environment:
      - POSTGRES_DB=poc_api
      - POSTGRES_PASSWORD=poc_password
      - POSTGRES_USER=poc_user
    image: postgres:10.1
    networks:
      - db_nw
    volumes:
      - "./docker_data/apidb:/var/lib/postgresql"

networks:
  db_nw:
    driver: bridge

volumes:
  docker_data:
