#!/bin/bash

CMD="$1"

if [[ "$CMD" == "build" ]]; then
  # *TBW*
  docker-compose up --build
elif [[ "$CMD" == "clean" || "$CMD" == "sandbox" ]]; then
  docker exec -it poc-api bash -c "cd /opt/api && PYTHONPATH=. python scripts/manager.py '$CMD'"
elif [[ "$CMD" == "psql" ]]; then
  *TBW*
elif [[ "$CMD" == "python" ]]; then
  docker exec -it poc-api bash -c "cd /opt/api && PYTHONPATH=. python -i scripts/shell.py"
elif [[ "$CMD" == "rebuild" ]]; then
  # *TBW*
  docker-compose up --build --force-recreate --no-deps -d
elif [[ "$CMD" == "rmdb" ]]; then
	# *TBW*
  docker exec -it poc-api bash -c "cd /opt/api && PYTHONPATH=. python -i repository/clean.py"
elif [[ "$CMD" == "restart" ]]; then
  # *TBW*
  docker-compose restart
elif [[ "$CMD" == "start" ]]; then
  docker-compose up
fi
